# Generated by Django 3.0.6 on 2020-05-29 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UrlMap',
            fields=[
                ('longurl', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('shorturl', models.CharField(max_length=4)),
            ],
        ),
    ]
