apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: urlshortener
  name: urlshortener
  namespace: app
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
    nodePort: 31000
  selector:
    app: urlshortener
  type: NodePort

