apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: mysql-db
  name: mysql-db
  namespace: app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql-db
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: mysql-db
    spec:
      volumes:
      - name: mysql-pv-storage
        persistentVolumeClaim:
          claimName: mysql-pv-claim
      containers:
      - image: mysql
        name: mysql
        ports:
        - containerPort: 3306
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-password
              key: password
        volumeMounts:
        - mountPath: "/var/lib/mysql"
          name: mysql-pv-storage
