apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: mysql-db
  name: mysql-db
  namespace: app
spec:
  ports:
  - port: 3306
    protocol: TCP
    targetPort: 3306
  selector:
    app: mysql-db
  type: ClusterIP
status:
  loadBalancer: {}
